# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen
image: alpine

include:
  - project: 'build_server/gitlab_ci_includes'
    file: 'api_publish.yml'
  - project: 'build_server/gitlab_ci_includes'
    file: 'software_catalogue.yml'
    
build_rock_18.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-wbc_ubuntu:18.04
  stage: build
  script:
    - aup --config
    - aup orogen/ctrl_lib
    - amake orogen/ctrl_lib

build_rock_20.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-wbc_ubuntu:20.04
  stage: build
  script:
    - aup --config
    - aup orogen/ctrl_lib
    - amake orogen/ctrl_lib

run_tests_18.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-wbc_ubuntu:18.04
  stage: test
  script:
  - aup --config
  - aup
  - aup orogen/ctrl_lib
  - amake orogen/ctrl_lib
  - /etc/init.d/omniorb4-nameserver start
  - source $AUTOPROJ_CURRENT_ROOT/env.sh
  - cd test
  - ruby test_cartesian_force_controller.rb
  - ruby test_cartesian_position_controller.rb
  - ruby test_cartesian_radial_potential_fields.rb
  - ruby test_joint_limit_avoidance.rb
  - ruby test_joint_position_controller.rb

